version: "3.5"

services:

  webhook:
    container_name: webhook
    restart: always
    image: webhook:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8801:8001"
