import pytest

from app import create_app


@pytest.fixture
def app():
    return create_app()


@pytest.mark.asyncio
async def test_basic_asgi_client(app):

    test_push = {
        "ref": "refs/heads/master",
        "before": "724b437722d9e6c83973c94767b7c13eba1d0296",
        "after": "1410d6b0db21898c99948c51bb0fc6b8570a69c2",
        "repository": {
            "id": 568341457,
            "node_id": "R_kgDOIeAz0Q",
            "name": "webhook",
            "full_name": "gaps-apps/webhook",
            "private": True,
            "owner": {
                "name": "gaps-apps",
                "email": None,
                "login": "gaps-apps",
                "id": 116283019,
                "node_id": "O_kgDOBu5Wiw",
                "avatar_url": "https://avatars.githubusercontent.com/u/116283019?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/gaps-apps",
                "html_url": "https://github.com/gaps-apps",
                "followers_url": "https://api.github.com/users/gaps-apps/followers",
                "following_url": "https://api.github.com/users/gaps-apps/following{/other_user}",
                "gists_url": "https://api.github.com/users/gaps-apps/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/gaps-apps/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/gaps-apps/subscriptions",
                "organizations_url": "https://api.github.com/users/gaps-apps/orgs",
                "repos_url": "https://api.github.com/users/gaps-apps/repos",
                "events_url": "https://api.github.com/users/gaps-apps/events{/privacy}",
                "received_events_url": "https://api.github.com/users/gaps-apps/received_events",
                "type": "Organization",
                "site_admin": False,
            },
            "html_url": "https://github.com/gaps-apps/webhook",
            "description": None,
            "fork": False,
            "url": "https://github.com/gaps-apps/webhook",
            "forks_url": "https://api.github.com/repos/gaps-apps/webhook/forks",
            "keys_url": "https://api.github.com/repos/gaps-apps/webhook/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/gaps-apps/webhook/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/gaps-apps/webhook/teams",
            "hooks_url": "https://api.github.com/repos/gaps-apps/webhook/hooks",
            "issue_events_url": "https://api.github.com/repos/gaps-apps/webhook/issues/events{/number}",
            "events_url": "https://api.github.com/repos/gaps-apps/webhook/events",
            "assignees_url": "https://api.github.com/repos/gaps-apps/webhook/assignees{/user}",
            "branches_url": "https://api.github.com/repos/gaps-apps/webhook/branches{/branch}",
            "tags_url": "https://api.github.com/repos/gaps-apps/webhook/tags",
            "blobs_url": "https://api.github.com/repos/gaps-apps/webhook/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/gaps-apps/webhook/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/gaps-apps/webhook/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/gaps-apps/webhook/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/gaps-apps/webhook/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/gaps-apps/webhook/languages",
            "stargazers_url": "https://api.github.com/repos/gaps-apps/webhook/stargazers",
            "contributors_url": "https://api.github.com/repos/gaps-apps/webhook/contributors",
            "subscribers_url": "https://api.github.com/repos/gaps-apps/webhook/subscribers",
            "subscription_url": "https://api.github.com/repos/gaps-apps/webhook/subscription",
            "commits_url": "https://api.github.com/repos/gaps-apps/webhook/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/gaps-apps/webhook/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/gaps-apps/webhook/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/gaps-apps/webhook/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/gaps-apps/webhook/contents/{+path}",
            "compare_url": "https://api.github.com/repos/gaps-apps/webhook/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/gaps-apps/webhook/merges",
            "archive_url": "https://api.github.com/repos/gaps-apps/webhook/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/gaps-apps/webhook/downloads",
            "issues_url": "https://api.github.com/repos/gaps-apps/webhook/issues{/number}",
            "pulls_url": "https://api.github.com/repos/gaps-apps/webhook/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/gaps-apps/webhook/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/gaps-apps/webhook/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/gaps-apps/webhook/labels{/name}",
            "releases_url": "https://api.github.com/repos/gaps-apps/webhook/releases{/id}",
            "deployments_url": "https://api.github.com/repos/gaps-apps/webhook/deployments",
            "created_at": 1668931726,
            "updated_at": "2022-11-20T08:10:11Z",
            "pushed_at": 1668936465,
            "git_url": "git://github.com/gaps-apps/webhook.git",
            "ssh_url": "git@github.com:gaps-apps/webhook.git",
            "clone_url": "https://github.com/gaps-apps/webhook.git",
            "svn_url": "https://github.com/gaps-apps/webhook",
            "homepage": None,
            "size": 24,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "Python",
            "has_issues": True,
            "has_projects": True,
            "has_downloads": True,
            "has_wiki": True,
            "has_pages": False,
            "has_discussions": False,
            "forks_count": 0,
            "mirror_url": None,
            "archived": False,
            "disabled": False,
            "open_issues_count": 0,
            "license": None,
            "allow_forking": False,
            "is_template": False,
            "web_commit_signoff_required": False,
            "topics": [],
            "visibility": "private",
            "forks": 0,
            "open_issues": 0,
            "watchers": 0,
            "default_branch": "master",
            "stargazers": 0,
            "master_branch": "master",
            "organization": "gaps-apps",
        },
        "pusher": {"name": "fuzz88", "email": "ivan@oschepkov.ru"},
        "organization": {
            "login": "gaps-apps",
            "id": 116283019,
            "node_id": "O_kgDOBu5Wiw",
            "url": "https://api.github.com/orgs/gaps-apps",
            "repos_url": "https://api.github.com/orgs/gaps-apps/repos",
            "events_url": "https://api.github.com/orgs/gaps-apps/events",
            "hooks_url": "https://api.github.com/orgs/gaps-apps/hooks",
            "issues_url": "https://api.github.com/orgs/gaps-apps/issues",
            "members_url": "https://api.github.com/orgs/gaps-apps/members{/member}",
            "public_members_url": "https://api.github.com/orgs/gaps-apps/public_members{/member}",
            "avatar_url": "https://avatars.githubusercontent.com/u/116283019?v=4",
            "description": None,
        },
        "sender": {
            "login": "fuzz88",
            "id": 8016584,
            "node_id": "MDQ6VXNlcjgwMTY1ODQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8016584?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fuzz88",
            "html_url": "https://github.com/fuzz88",
            "followers_url": "https://api.github.com/users/fuzz88/followers",
            "following_url": "https://api.github.com/users/fuzz88/following{/other_user}",
            "gists_url": "https://api.github.com/users/fuzz88/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fuzz88/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fuzz88/subscriptions",
            "organizations_url": "https://api.github.com/users/fuzz88/orgs",
            "repos_url": "https://api.github.com/users/fuzz88/repos",
            "events_url": "https://api.github.com/users/fuzz88/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fuzz88/received_events",
            "type": "User",
            "site_admin": False,
        },
        "created": False,
        "deleted": False,
        "forced": False,
        "base_ref": None,
        "compare": "https://github.com/gaps-apps/webhook/compare/724b437722d9...1410d6b0db21",
        "commits": [
            {
                "id": "1410d6b0db21898c99948c51bb0fc6b8570a69c2",
                "tree_id": "10829d8eaa29460045c96e516d3e2b3bbbe0c677",
                "distinct": True,
                "message": "test logger",
                "timestamp": "2022-11-20T17:27:41+08:00",
                "url": "https://github.com/gaps-apps/webhook/commit/1410d6b0db21898c99948c51bb0fc6b8570a69c2",
                "author": {
                    "name": "fuzz88",
                    "email": "ivan@oschepkov.ru",
                    "username": "fuzz88",
                },
                "committer": {
                    "name": "fuzz88",
                    "email": "ivan@oschepkov.ru",
                    "username": "fuzz88",
                },
                "added": [],
                "removed": [],
                "modified": ["app/app.py"],
            }
        ],
        "head_commit": {
            "id": "1410d6b0db21898c99948c51bb0fc6b8570a69c2",
            "tree_id": "10829d8eaa29460045c96e516d3e2b3bbbe0c677",
            "distinct": True,
            "message": "test logger",
            "timestamp": "2022-11-20T17:27:41+08:00",
            "url": "https://github.com/gaps-apps/webhook/commit/1410d6b0db21898c99948c51bb0fc6b8570a69c2",
            "author": {
                "name": "fuzz88",
                "email": "ivan@oschepkov.ru",
                "username": "fuzz88",
            },
            "committer": {
                "name": "fuzz88",
                "email": "ivan@oschepkov.ru",
                "username": "fuzz88",
            },
            "added": [],
            "removed": [],
            "modified": ["app/app.py"],
        },
    }

    _, response = await app.asgi_client.post("/gh", headers={"x-hub-signature-256": "test"})

    assert response.status == 200
